# Generated by Django 3.1.1 on 2020-10-20 18:50

from django.db import migrations, models
# Generated by Django 3.1.1 on 2020-10-19 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_text', models.CharField(max_length=200)),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
    ]
