# Generated by Django 3.1.1 on 2020-10-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_task'),
        ('donations', '0003_auto_20201021_0144'),
    ]

    operations = [
    ]
