# Generated by Django 3.1.1 on 2020-10-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_orgs',
            field=models.ManyToManyField(to='donations.Organization'),
        ),
    ]
