# Generated by Django 3.1.1 on 2020-10-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_profile_favorite_orgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_orgs',
        ),
    ]
