# Generated by Django 3.1.1 on 2020-11-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_remove_profile_favorite_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_orgs',
            field=models.ManyToManyField(to='donations.Organization'),
        ),
    ]
