# Generated by Django 3.1.1 on 2020-11-06 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_order_product'),
        ('donations', '0006_profile_favorite_orgs'),
    ]

    operations = [
    ]
