# Generated by Django 3.1.1 on 2020-11-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_merge_20201105_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_orgs',
        ),
        migrations.AddField(
            model_name='organization',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
