# Generated by Django 3.1.1 on 2020-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20201112_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='price',
            new_name='fundsGoal',
        ),
        migrations.AddField(
            model_name='organization',
            name='fundsRaised',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
