# Generated by Django 3.1.1 on 2020-11-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_task_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_img_link',
            field=models.CharField(default='https://mdbootstrap.com/img/Photos/Others/images/16.jpg', max_length=200),
        ),
    ]
