# Generated by Django 3.1.1 on 2020-11-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_task_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_owner',
        ),
    ]
