# Generated by Django 3.1.1 on 2020-11-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_task_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_owner',
        ),
        migrations.AddField(
            model_name='task',
            name='covfefe',
            field=models.BooleanField(default=False),
        ),
    ]
