# Generated by Django 3.1.1 on 2020-11-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_remove_task_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done2',
            field=models.BooleanField(default=False),
        ),
    ]
