# Generated by Django 3.1.1 on 2020-11-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_auto_20201118_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_owner',
        ),
    ]
