# Generated by Django 3.1.1 on 2020-11-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_auto_20201120_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_img_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
