# Generated by Django 3.1.1 on 2020-11-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_auto_20201120_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_orgs',
            field=models.ManyToManyField(to='donations.Organization'),
        ),
    ]
