# Generated by Django 3.1.1 on 2020-11-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_profile_favorite_orgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='fundsGoal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fundsRaised',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
