# Generated by Django 3.1.1 on 2020-11-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_auto_20201120_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tasksCompleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='totalDonated',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
