# Generated by Django 3.1.1 on 2020-11-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_auto_20201122_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description_text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='task',
            name='description_text',
            field=models.CharField(max_length=2000),
        ),
    ]
